
[package]
name = "__PAC_NAME__"
version = "0.0.1"
author = ["__USER_NAME__"]

[path]
lib_dirs = []
libs = []
includes = ["./include"]
source = "./src"
dest = "./build"

[build]
compiler = "g++"
args = [
    "-Wall", "-Wextra", "-std=c++11", "-O2"
]

